version: '3.5'

services:
  database:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    expose:
      - "5432"
  server:
    image: mitre/heimdall2
    restart: unless-stopped
    environment:
      HEIMDALL_SERVER_PORT: 3000
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRE_TIME: 60s
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - "database"
