name: Push InSpecJS to NPM

on:
  release:
    types: [published]

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
          registry-url: 'https://registry.npmjs.org'
      
      - name: Remove frontend and backend code to ensure the proper dependencies are declared in the inspecjs package.json
        run: |
        rm -rf apps/frontend
        rm -rf apps/backend

      - name: Install project dependencies
        run: yarn install --frozen-lockfile

      - name: Build InSpecJS package files
        run: yarn inspecjs build

      - name: Build tarball for publishing
        run: yarn inspecjs pack

      - name: Publish InSpecJS to NPM
        run: npm publish --access public apps/frontend/inspecjs*.tgz
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
