name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    steps:
     - uses: actions/checkout@v2
     - name: Setup Node.js
       uses: actions/setup-node@v1
       with:
        node-version: '12.x'

     - name: Install dependencies
       run: lerna bootstrap --hoist

     - name: Run lint
       run: lerna run lint:ci

     - name: Copy .env-ci to .env
       run: cp apps/backend/test/.env-ci apps/backend/.env

     - name: Create/migrate db
       run: |
        lerna exec "npx sequelize-cli db:migrate" --scope heimdall-server
        lerna exec "npx sequelize-cli db:migrate" --scope heimdall-server

     - name: Build frontend
       run: |
        lerna run build --scope heimdall-lite

     - name: Run test coverage
       run: lerna run test:ci-cov

     - name: Run frontend tests
       run: lerna run test:unit --scope heimdall-lite

     - name: Run e2e tests
       run: lerna run test:e2e

     - name: Run e2e UI tests
       run: lerna run test:ui
