name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    steps:
     - uses: actions/checkout@v2

     - name: Cache node modules
       uses: actions/cache@v2
       env:
         cache-name: cache-node-modules
       with:
         # npm cache files are stored in `~/.npm` on Linux/macOS
         path: ~/.npm
         key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
         restore-keys: |
           ${{ runner.os }}-build-${{ env.cache-name }}-
           ${{ runner.os }}-build-
           ${{ runner.os }}-

     - name: Setup Node.js
       uses: actions/setup-node@v1
       with:
        node-version: '12.x'

     - name: Install lerna and dev dependencies
       run: npm install

     - name: Install project dependencies
       run: npx lerna bootstrap --hoist

     - name: Run lint
       run: npx lerna run lint:ci

     - name: Copy .env-ci to .env
       run: cp apps/backend/test/.env-ci apps/backend/.env

     - name: Create/migrate db
       run: |
        npx lerna exec "npx sequelize-cli db:create" --scope heimdall-server
        npx lerna exec "npx sequelize-cli db:migrate" --scope heimdall-server

     - name: Build frontend and server for E2E UI tests
       run: |
        npx lerna run build

     - name: Run test coverage
       run: npx lerna run test:ci-cov --stream

     - name: Run frontend tests
       run: npx lerna run test --scope heimdall-lite --stream

     - name: Run e2e tests
       run: npx lerna run test:e2e --stream

     - name: Run e2e UI tests
       run: npx lerna run test:ui --stream
